### ISSUE TITLE
Missing ITINERANT RESTAURANT

### ISSUE THREAD

**Issue by seansummers** [HackMichiana/restaurant-sustainability#1]
Filter may be missing a few (food trucks?):

Classification_Code: | RESTIT
Classification_Description: | ITINERANT RESTAURANT

**Comment by seansummers** [comment]
Well, it looks like food trucks are a different thing, too:

Classification_Code: | FVV
Classification_Description: | FOOD VENDING VEHICLES

**Comment by trwiley** [comment]
Included FVVs and RESTITs in the script filtering.
