### ISSUE TITLE
Additional documentation

### ISSUE THREAD

**Issue by seansummers** [HackMichiana/restaurant-sustainability#4]
It looks like the source data is available at the [South Bend Open Data Portal, Business Licenses](http://data-southbend.opendata.arcgis.com/datasets/business-licenses/geoservice), last updated 2017-07-28.

After playing around a bit, I have a basic [ArcGIS API Query](https://services1.arcgis.com/0n2NelSAfR7gTkr1/arcgis/rest/services/Business_Licenses/FeatureServer/0/query?orderByFields=Business_Name,License_Fiscal_Year%20ASC&where=Classification_Code%20IN%20('RESTAM','RESTZ','RESTIT','FVV')&outFields=Business_Name,Street_Address,Zip,Business_Phone_Number,License_Status,License_Fiscal_Year&outSR=4326&f=json) that seems to return a superset of the data being parsed, pending some of the duplicate resolution and status issues (refer to Issue #3 ) .

**Comment by trwiley** [comment]
Added link to the original data source in the readme - probably not enough to close the issue?

**Comment by seansummers** [comment]
Unless you want to put the query link to work to do some preprocessing, we can close this. Even if we use the link to create mostly the dataset the code here produces, the dedupe and sanity checks will still need to be worked out (and probably not as part of this thread anyway).
